# Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "sda@asdads.com",
    "password": "sdasdasddsa"
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/12


### Find All users with a given email
GET http://localhost:3000/auth?email=sda@asdads.com


### Delete a user with a given ID
DELETE http://localhost:3000/auth/12


### Update a user with a given ID
PATCH http://localhost:3000/auth/12
Content-Type: application/json

{
    "email": "aa@gmail.com"
}